import type { EventCard } from "@/lib/types/meetmap-discovery";

type MockMeetMapEvent = EventCard & {
  popularityScore: number;
};

export const mockMeetMapEvents: MockMeetMapEvent[] = [
  {
    id: "haifa-sunset-jazz-01",
    title: "Sunset Jazz at the Port",
    city: "Haifa",
    category: "music",
    startsAt: "2026-03-27T19:30:00+02:00",
    description: "Live jazz set at Haifa Port with open seating and a social crowd.",
    popularityScore: 95,
  },
  {
    id: "haifa-carmel-food-02",
    title: "Carmel Market Food Walk",
    city: "Haifa",
    category: "food",
    startsAt: "2026-03-28T11:00:00+02:00",
    description: "Small-group tasting walk through local stalls and street food spots.",
    popularityScore: 91,
  },
  {
    id: "haifa-gallery-night-03",
    title: "Downtown Gallery Night",
    city: "Haifa",
    category: "art",
    startsAt: "2026-03-26T20:00:00+02:00",
    description: "Casual art evening with open studios, short talks, and drinks.",
    popularityScore: 84,
  },
  {
    id: "haifa-boardgames-04",
    title: "Board Games and Beer",
    city: "Haifa",
    category: "social",
    startsAt: "2026-03-29T18:30:00+03:00",
    description: "Friendly meetup for new people, light games, and a relaxed pub vibe.",
    popularityScore: 78,
  },
  {
    id: "tel-aviv-beach-run-05",
    title: "Friday Beach Run",
    city: "Tel Aviv",
    category: "sports",
    startsAt: "2026-03-27T06:45:00+02:00",
    description: "Morning group run along the promenade with beginner and intermediate pace.",
    popularityScore: 93,
  },
  {
    id: "tel-aviv-open-air-dj-06",
    title: "Open-Air DJ Session",
    city: "Tel Aviv",
    category: "music",
    startsAt: "2026-03-28T21:00:00+02:00",
    description: "Outdoor electronic music set near the waterfront with a young crowd.",
    popularityScore: 97,
  },
  {
    id: "tel-aviv-ceramics-07",
    title: "Beginner Ceramics Workshop",
    city: "Tel Aviv",
    category: "art",
    startsAt: "2026-03-30T18:00:00+03:00",
    description: "Hands-on clay workshop focused on simple forms and social conversation.",
    popularityScore: 76,
  },
  {
    id: "jerusalem-night-market-08",
    title: "Mahane Yehuda Night Bites",
    city: "Jerusalem",
    category: "food",
    startsAt: "2026-03-26T19:00:00+02:00",
    description: "Evening tasting route through the market with local recommendations.",
    popularityScore: 92,
  },
  {
    id: "jerusalem-museum-social-09",
    title: "Museum Meetup for Young Adults",
    city: "Jerusalem",
    category: "social",
    startsAt: "2026-03-31T18:45:00+03:00",
    description: "Social meetup around a rotating exhibition followed by coffee nearby.",
    popularityScore: 74,
  },
  {
    id: "jerusalem-acoustic-10",
    title: "Acoustic Courtyard Night",
    city: "Jerusalem",
    category: "music",
    startsAt: "2026-03-28T20:30:00+02:00",
    description: "Intimate acoustic performances in a stone courtyard setting.",
    popularityScore: 88,
  },
  {
    id: "karmiel-hike-11",
    title: "Morning Community Hike",
    city: "Karmiel",
    category: "outdoor",
    startsAt: "2026-03-27T08:00:00+02:00",
    description: "Easy regional trail hike with coffee stop and open signup.",
    popularityScore: 81,
  },
  {
    id: "karmiel-folk-dance-12",
    title: "Folk Dance in the Square",
    city: "Karmiel",
    category: "social",
    startsAt: "2026-03-28T19:30:00+02:00",
    description: "Open community dance circle with beginners welcome.",
    popularityScore: 79,
  },
];
